// 从 play.bat 里抽出「会被 cmd 解析的行」，用于 diff 与纯 ASCII 守卫。
//
// 为什么需要它：play.bat 从 2026-10-08 起带中文游玩说明（写在 REM 注释里，
// cmd 会整行忽略），所以**整文件 diff** 不再可用 —— 任何一次改文案都会把
// 几十行中文顶动，让人看不出真正变了什么。
//
// ⇒ 把可执行行单独抽出来落盘。改动 review 时 diff 这个文件，
//   中文文案要 review 就直接看 play.bat。
//
// 同时它就是 PowerShellScriptEncodingTest / InfiniteReserveWiringTest
// 那两条"可执行行必须纯 ASCII"判据的**唯一事实源** ——
// 守卫读抽出来的行，而不是各自重新实现一遍"哪些行算可执行"。
// （两处各写一遍，就是下一次两边判据不一致的起点。）
//
// 用法：node tmp/extract_play_exec.js [--check]
//   无参   = 写出 tmp/play_exec.txt
//   --check = 只比对，不写；不一致则退出 1
'use strict';

const fs = require('fs');
const path = require('path');

const PROJ = process.env.SKYISLAND_PROJ || 'F:/minecraftspace';
const BAT = path.join(PROJ, 'play.bat');
const OUT = path.join(PROJ, 'tmp', 'play_exec.txt');

const CHECK = process.argv.includes('--check');

/**
 * 哪些行算「会被 cmd 解析的行」。
 *
 * 判定规则刻意保守：只把明确的注释形式排除掉，其余一律算可执行。
 * 理由是判据的方向性 —— 误把注释当可执行（假红）只是让守卫变吵，
 * 而误把可执行当注释（**假绿**）会让守卫失去作用。宁可吵。
 */
function isExecutable(line) {
  const t = line.trim();
  if (t === '') return false;
  if (t.startsWith('REM')) return false;    // REM 注释（含 "REM " 与 "REM"）
  if (t.startsWith('::')) return false;    // :: 注释
  if (t.startsWith('@')) {
    // "@echo off" 是真正会被解析的；"@REM ..." 不太可能出现在本文件，
    // 保守起见把 @ 开头的也算可执行 —— 它至少会执行 echo/pause。
    return true;
  }
  return true;
}

const src = fs.readFileSync(BAT, 'utf8');
const lines = src.split(/\r?\n/);
const exec = [];
const violations = [];
lines.forEach((line, i) => {
  if (!isExecutable(line)) return;
  exec.push(line);
  for (let k = 0; k < line.length; k++) {
    if (line.charCodeAt(k) > 127) {
      violations.push({ line: i + 1, offset: k, text: line.trim() });
      break;
    }
  }
});

const body = [
  '# GENERATED by tmp/extract_play_exec.js -- do not edit, do not commit.',
  '# Executable lines of play.bat (comments stripped). Use this for diffing.',
  '# Count: ' + exec.length,
  '',
].concat(exec).join('\n') + '\n';

if (CHECK) {
  const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (prev === null) {
    console.error('[extract] ' + OUT + ' missing — run without --check first');
    process.exit(2);
  }
  if (prev !== body) {
    console.error('[extract] play.bat executable lines CHANGED since the last extract.');
    console.error('  run: node tmp/extract_play_exec.js');
    process.exit(1);
  }
  console.log('[extract] play.bat executable lines unchanged (' + exec.length + ' lines).');
} else {
  fs.writeFileSync(OUT, body, 'utf8');
  console.log('[extract] wrote ' + OUT + '  (' + exec.length + ' executable lines)');
}

if (violations.length > 0) {
  console.error('');
  console.error('[extract] ★ 非 ASCII 出现在**可执行行**（GBK 的 cmd.exe 会读崩）：');
  for (const v of violations) {
    console.error('  line ' + v.line + ' 偏移 ' + v.offset + ': <' + v.text + '>');
  }
  console.error('');
  console.error('  ⇒ 中文只能写在 REM 注释行；set / java / if / for 必须纯 ASCII。');
  process.exit(3);
}

console.log('[extract] all executable lines are pure ASCII.');